### ISSUE TITLE
Odd behaviour on planner

### ISSUE THREAD

**Issue by cgutteridge** [SourceKettle/sourcekettle#464]
on the milestone planner page: When I assign a new task not on the milestone to myself it moves it to "major" on the page, but doesn't do anything to the database.

**Comment by antineutron** [comment]
Works for changing the status too. It's because the (terrible) javascript sees it's changed, and moves it into the appropriate column. This is fine in the normal sprint board, as everything's actually in the milestone, but when you've got things that aren't in this milestone it just blindly puts it into the column with the correct priority when anything changes.
